import type { Metadata } from 'next'
import { Inter, Red_Hat_Display } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const redhat = Red_Hat_Display({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="synthwave">
      <body className={redhat.className}>{children}</body>
    </html>
  )
}
